dist: xenial
language: python
python:
  - 3.7
  - 3.6
  - 3.7-dev
before_install:
  - openssl aes-256-cbc -K $encrypted_adeed957da41_key -iv $encrypted_adeed957da41_iv
    -in email_password.txt.enc -out src/tests/email_password.txt -d
install:
  - pip install -r requirements.txt
script:
  - cd src/tests
  - python test-src-mail.py
  - python test-utils-generic.py
