sudo: required
dist: xenial
language: python
before_install:
  - export TZ=america/new-york
  - openssl aes-256-cbc -K $encrypted_adeed957da41_key -iv $encrypted_adeed957da41_iv
    -in encrypted_files.tar.gz.enc -out encrypted_files.tar.gz -d
  - tar xvf encrypted_files.tar.gz
  - mv src/email_password.txt src/tests
  - mv src/firestore_creds.json src/tests
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: Python3.6
      python: 3.6
      script:
        - cd src/tests
        - python test-src-database.py
        - python test-src-mail.py
        - python test-utils-generic.py
        - python test-utils-datetime_utils.py
    - stage: Python3.7
      python: 3.7
      script:
        - cd src/tests
        - python test-src-database.py
        - python test-src-mail.py
        - python test-utils-generic.py
        - python test-utils-datetime_utils.py
    - stage: Python3.7-dev
      python: 3.7-dev
      script:
        - cd src/tests
        - python test-src-database.py
        - python test-src-mail.py
        - python test-utils-generic.py
        - python test-utils-datetime_utils.py
    - stage: Docker-Container
      python: 3.7
      services: docker
      script:
        - docker build -f Dockerfile.dev -t mattgleich/server-monitor:latest .
        - docker run mattgleich/server-monitor
stages:
  - Python3.6
  - Python3.7
  - Python3.7-dev
  - Docker-Container
