sudo: required
dist: xenial
before_install:
  - export TZ=america/new-york
  - openssl aes-256-cbc -K $encrypted_adeed957da41_key -iv $encrypted_adeed957da41_iv
    -in encrypted_files.tar.gz.enc -out encrypted_files.tar.gz -d
  - tar xvf encrypted_files.tar.gz
  - mv src/email_password.txt src/tests
  - mv src/firestore_creds.json src/tests
jobs:
  include:
    - stage: Python3.6
      language: python
      python: 3.6
      install: pip install -r requirements.txt
      script:
        - cd src/tests
        - pytest --emoji
    - stage: Python3.7
      language: python
      python: 3.7
      install: pip install -r requirements.txt
      script:
        - cd src/tests
        - pytest --emoji
    - stage: Docker-Container
      language: generic
      services: docker
      script:
        - docker build -f Dockerfile.dev -t mattgleich/server-monitor:latest .
        - docker run -e CI=true mattgleich/server-monitor
stages:
  - Docker-Container
  - Python3.7
  - Python3.6
